SERVER_PORT: ":8443"
SERVER_SSL_ENABLED: false
SERVER_ENABLING_PROFILE: true

#mysql configurations
MYSQL_USERNAME: root
MYSQL_PASSWORD: Develop@2021
DB_NAME: he
DB_DRIVER: mysql
CONNECTION_STRING: tcp(127.0.0.1:3306)/