SERVER_PORT: ":8080"
SERVER_SSL_ENABLED: false
SERVER_ENABLING_PROFILE: true
SERVICE_VERSION: 1.0.0

#mysql configurations
MYSQL_USERNAME: root
MYSQL_PASSWORD: makmoinee@2018
DB_NAME: he
DB_DRIVER: mysql
CONNECTION_STRING: tcp(localhost:3306)/